// <auto-generated />
using System;
using MiGenteEnLinea.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiGenteEnLinea.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MiGenteDbContext))]
    [Migration("20251030184500_RehashTestUsersToIdentity")]
    partial class RehashTestUsersToIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Esta migración solo actualiza datos, no modifica el schema
            // Por lo tanto, el modelo target es el mismo que la migración anterior
        }
    }
}
